language: ruby
sudo: false
rvm:
  - 2.2.0
bundler_args: "--without development production --deployment --jobs=3 --retry=3"
cache: :bundler
before_script:
  - cp config/database.yml.dev config/database.yml
