language: ruby
rvm:
  - 2.1.5
bundler_args: "--without development production --deployment --jobs=3 --retry=3"
cache: :bundler
before_script:
  - cp config/database.yml.dev config/database.yml
addons:
  code_climate:
    repo_token: 344f2271d2b725ba0ac6a12dc919d918835e837a2bc76b4bfa7f0b840b3d6b66
